name: Check
on:
  - push
  - pull_request
jobs:
  default:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build and run checks
        uses: cake-build/cake-action@v1.1.1
        with:
          target: Check
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
