name: check
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cake-build/cake-action@v1.1.1
        with:
          target: Check
